#!/bin/sh

HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin:$HOME/bin:/opt/homebrew/bin:$PATH"
export MANPAGER='nvim +Man!'
export MANWIDTH=999


# pyenv
function pyenv_configuration {
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
}

export PYENV_ROOT="$HOME/.pyenv"

if [ -d "$PYENV_ROOT" ]; then
    pyenv_configuration
else
    PLATFORM=$(uname)
    if [[ ${PLATFORM} == 'Darwin' ]]; then        ## MAC
        brew install pyenv
        brew install pyenv-virtualenv
        pyenv_configuration
    elif [[ ${PLATFORM} == 'Linux' ]]; then      ## Linux
        git clone https://github.com/pyenv/pyenv.git ~/.pyenv
        git clone https://github.com/pyenv/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv
        pyenv_configuration
    fi
fi