#!/bin/sh

# Custom
alias ls='ls -la'
alias cdw='cd ~/workplace'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'
# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

## GIT ##
alias gl="git log --oneline | cat"
alias gp='git push -fu origin $(git rev-parse --abbrev-ref HEAD)'
alias bg='osascript -e "tell application \"iTerm\" to tell current session of current window to set background color to {0, 0, 0, 0}"'
