#!/bin/sh

HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin:$HOME/bin:/opt/homebrew/bin:$PATH"
export MANPAGER='nvim +Man!'
export MANWIDTH=999

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
if [ -d "$PYENV_ROOT" ]; then
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
  # Control will enter here if $DIRECTORY exists.
fi
